# Generated by Django 4.2.6 on 2023-10-29 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='rate',
            field=models.IntegerField(default=0),
        ),
    ]
