# Generated by Django 4.2.6 on 2023-10-29 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_projects_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='current_donation',
            field=models.IntegerField(default=0),
        ),
    ]
